server:
  port: 8080

# springboot默认上传文件大小最高为1MB，通过这个配置文件可以自定义设计上传文件最高的大小
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql:///exam_system_new?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: 1234
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称
      # 全局时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# 默认情况下Knife4j为该接口生成的接口文档如下图所示，其中的queryVo参数错误会被误识别成json格式！
springdoc:
  default-flat-param-object: true
#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 逻辑删除功能只对Mybatis-Plus自动注入的sql起效，也就是说，对于手动在`Mapper: xml`文件配置的sql不会生效，需要单独考虑。:
    auto-mapping-behavior: full #开启嵌套自动映射
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体属性名(配置后可以忽略不配置步骤二)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

minio:
  endpoint: http://192.168.100.168:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: onlinebucket
